import type { Metadata } from 'next';
import type { ReactNode } from 'react';
import { SanityLive } from '../sanity/lib/live';
import './globals.css';

export const metadata: Metadata = {
  title: 'Site Foundry Starter',
  description: 'Next.js + Sanity starter generated by Site Foundry.',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        {children}
        <SanityLive />
      </body>
    </html>
  );
}
