export const pageBySlugQuery = `
  *[_type == "page" && slug.current == $slug][0]{
    _id,
    _type,
    _createdAt,
    _updatedAt,
    title,
    "slug": slug.current,
    pageBuilder[]{
      ...,
      media{
        ...,
        asset->{
          url
        }
      },
      ctas[]{
        ...,
        link{
          ...,
          page->{
            _type,
            "slug": slug.current
          },
          file{
            asset->{
              url
            }
          }
        }
      },
      items[]{
        ...,
        icon{
          ...,
          asset->{
            url
          }
        },
        logo{
          ...,
          asset->{
            url
          }
        },
        avatar{
          ...,
          asset->{
            url
          }
        },
        cta{
          ...,
          link{
            ...,
            page->{
              _type,
              "slug": slug.current
            },
            file{
              asset->{
                url
              }
            }
          }
        }
      }
    }
  }
`;
